# Generated by Django 5.0.4 on 2024-04-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_aboutus_backgroundimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='testimonials/')),
                ('content', models.TextField()),
                ('stars', models.IntegerField()),
            ],
        ),
    ]
