# Generated by Django 5.0.4 on 2024-04-21 01:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_testimonial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='from_email',
            new_name='email',
        ),
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='company',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
    ]
